# Generated by Django 5.0.7 on 2024-07-11 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("scientific_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("habitat", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="PlantImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="plant_images/")),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_healthy", models.BooleanField(default=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="plants.plant",
                    ),
                ),
            ],
        ),
    ]
