# Generated by Django 5.0.7 on 2024-07-11 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("disease_detection", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Disease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
                ("symptoms", models.TextField()),
                ("treatment", models.TextField()),
                ("prevention", models.TextField()),
                (
                    "affected_parts",
                    models.ManyToManyField(
                        related_name="diseases", to="disease_detection.plantpart"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disease_detection.diseasecategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiseaseImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="disease_images/")),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "disease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="plant_disease.disease",
                    ),
                ),
            ],
        ),
    ]
