# Generated by Django 5.0.7 on 2024-07-15 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plant_disease", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiseaseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Disease Categories",
            },
        ),
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("scientific_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("habitat", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="PlantPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="disease",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="plant_disease.diseasecategory",
            ),
        ),
        migrations.CreateModel(
            name="PlantImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="plant_images/")),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_healthy", models.BooleanField(default=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="plant_disease.plant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EuropeanDisease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
                ("symptoms", models.TextField()),
                ("treatment", models.TextField()),
                ("prevention", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plant_disease.diseasecategory",
                    ),
                ),
                (
                    "affected_parts",
                    models.ManyToManyField(
                        related_name="european_diseases", to="plant_disease.plantpart"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="disease",
            name="affected_parts",
            field=models.ManyToManyField(
                related_name="diseases", to="plant_disease.plantpart"
            ),
        ),
    ]
