# Generated by Django 5.0.7 on 2024-07-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AI_tools", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="llm_response",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="user_message",
        ),
        migrations.AddField(
            model_name="conversation",
            name="llm_name",
            field=models.CharField(default="AI_Conversation", max_length=255),
        ),
        migrations.AddField(
            model_name="conversation",
            name="llm_responses",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="conversation",
            name="user_messages",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
