# Generated by Django 5.0.7 on 2024-08-07 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_tools', '0002_remove_conversation_llm_response_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NDVI', models.CharField(max_length=50)),
                ('leaf_area_index', models.CharField(max_length=50)),
                ('chlorophyll_content', models.CharField(max_length=50)),
                ('crop_water_stress_index', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drone_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('last_maintenance', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PestAndDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected', models.JSONField()),
                ('detection_rate', models.CharField(max_length=50)),
                ('treatment_recommended', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SoilHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pH', models.CharField(max_length=50)),
                ('organic_matter', models.CharField(max_length=50)),
                ('nitrogen', models.CharField(max_length=50)),
                ('phosphorus', models.CharField(max_length=50)),
                ('potassium', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.TextField()),
                ('capture_time', models.DateTimeField(auto_now_add=True)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AI_tools.drone')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_data', models.JSONField()),
                ('analysis_time', models.DateTimeField(auto_now_add=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AI_tools.image')),
            ],
        ),
    ]
