# this is returned by the agents system from Elnamaki Haive . 
def get_agents():
    agents = [
        {
            'id': 'chain-agent',
            'logo': 'PC',
            'color': 'rgba(46, 204, 113, 0.8)',
            'title': 'PlantChain AI Agent (LLama3.1 405B)',
            'description': 'Advanced AI agent for managing and optimizing the entire PlantChain ecosystem.',
            'stats': [
                {'value': '99.1%', 'label': 'Efficiency'},
                {'value': '0.01s', 'label': 'Response Time'},
                {'value': '100GB', 'label': 'Model Size'},
            ],
            'button_text': 'Deploy Agent',
            'is_main': True,
            'background_image': 'https://img.freepik.com/premium-photo/green-circuit-board-with-plant-growing-out-it_398492-661.jpg',
        },
        {
            'id': 'disease-identifier',
            'logo': 'DI',
            'color': '#e74c3c',
            'title': 'Disease Identifier Agent (GPT Vesion)',
            'description': 'AI-powered agent for identifying and diagnosing plant diseases in real-time.',
            'stats': [
                {'value': '91.5%', 'label': 'Accuracy'},
                {'value': '0.3s', 'label': 'Detection Time'},
                {'value': 'null', 'label': 'Model Size'},
            ],
            'button_text': 'Deploy Agent',
            'is_main': False,
        },
        {
            'id': 'swarm-agents',
            'logo': 'SA',
            'color': '#3498db',
            'title': 'Swarm Agents for Fields (LLama3.1 405B)',
            'description': 'Coordinated AI agents for monitoring and managing large agricultural areas.',
            'stats': [
                {'value': '91.7%', 'label': 'Coverage'},
                {'value': '0.05s', 'label': 'Response Time'},
                {'value': '100GB', 'label': 'Agent Size'},
            ],
            'button_text': 'Deploy Swarm',
            'is_main': False,
        },
        {
            'id': 'search-web-agents',
            'logo': 'SW',
            'color': '#9b59b6',
            'title': 'Search web Agents (multi LLMs)',
            'description': 'Comprehensive AI agent for continuous monitoring and analysis of crop health and growth.',
            'stats': [
                {'value': '89.3%', 'label': 'Accuracy'},
                {'value': '1m', 'label': 'Update Interval'},
                {'value': '100GB', 'label': 'System Size'},
            ],
            'button_text': 'Deploy Agents',
            'is_main': False,
        },
        {
            'id': 'garden-monitoring',
            'logo': 'GM',
            'color': '#f39c12',
            'title': 'Garden Monitoring Agent (LLama3.1 405B)',
            'description': 'AI agent for monitoring and optimizing all related garden operations.',
            'stats': [
                {'value': '90.9%', 'label': 'Uptime'},
                {'value': '0.1s', 'label': 'Block Time'},
                {'value': '100GB', 'label': 'Agent Size'},
            ],
            'button_text': 'Deploy Agent',
            'is_main': False,
        },
        {
            'id': 'science-agent',
            'logo': 'SA',
            'color': '#1abc9c',
            'title': 'Science Agent (LLama3.1 405B)',
            'description': 'AI-powered agent for conducting and analyzing agricultural research and experiments.',
            'stats': [
                {'value': '97.8%', 'label': 'Accuracy'},
                {'value': '1h', 'label': 'Analysis Time'},
                {'value': '100GB', 'label': 'Model Size'},
            ],
            'button_text': 'Deploy Agent',
            'is_main': False,
        },
        {
            'id': 'dataset-agent',
            'logo': 'DA',
            'color': '#34495e',
            'title': 'Dataset Agent (LLama3.1 405B)',
            'description': 'AI agent for managing, cleaning, and analyzing large agricultural datasets.',
            'stats': [
                {'value': '99.5%', 'label': 'Data Quality'},
                {'value': '5m', 'label': 'Processing Time'},
                {'value': '100GB', 'label': 'Agent Size'},
            ],
            'button_text': 'Deploy Agent',
            'is_main': False,
        },
        {
            'id': 'satellite-data',
            'logo': 'SD',
            'color': '#2ecc71',
            'title': 'Satellite Data Agent (LLama3.1 405B)',
            'description': 'AI agent for processing and analyzing satellite imagery for agricultural insights.',
            'stats': [
                {'value': '98.9%', 'label': 'Accuracy'},
                {'value': '10m', 'label': 'Update Interval'},
                {'value': '100GB', 'label': 'Model Size'},
            ],
            'button_text': 'Deploy Agent',
            'is_main': False,
        },
        {
            'id': 'weather-agent',
            'logo': 'WA',
            'color': '#e67e22',
            'title': 'Weather Agent (LLama3.1 405B)',
            'description': 'AI-powered agent for accurate weather forecasting and climate analysis for agriculture.',
            'stats': [
                {'value': '95.7%', 'label': 'Forecast Accuracy'},
                {'value': '15m', 'label': 'Update Interval'},
                {'value': '100GB', 'label': 'Model Size'},
            ],
            'button_text': 'Deploy Agent',
            'is_main': False,
        },
    ]
    
    return agents